name: 'Checks'
description: 'Some checks I apply to my personal projects.'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Find trailing spaces
      run: find . -type f -not -path "./.git/*" -exec grep -Iq . {} \; -print | xargs -L1 sed -i 's/[[:space:]]*$//'
      shell: bash
    - name: Generate suggestion by reviewdog
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: update-dependabot
        fail_on_error: true
