name: 'Checks'
description: 'Some checks I apply to my personal projects.'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Find trailing spaces
      run: find . -type f -not -path "./.git/*" -exec grep -Iq . {} \; -print | xargs -L1 sed -i 's/[[:space:]]*$//'
      shell: bash
    - name: Generate suggestion by reviewdog
      uses: reviewdog/action-suggester@v1
      with:
        fail_on_error: true
    - name: Run update-dependabot
      run: |
        pushd `mktemp -d` &&
        version=$(
          curl -s https://api.github.com/repos/black-desk/update-dependabot/releases/latest |
          python3  -c 'import sys, json; print(json.load(sys.stdin)["tag_name"].lstrip("v"))'
        ) &&
        curl -LJ "https://github.com/black-desk/update-dependabot/releases/latest/download/update-dependabot_${version}_linux_amd64.tar.gz" | tar zxf - &&
        ./update-dependabot -D "$GITHUB_WORKSPACE" &&
        popd
      shell: bash
    - name: Generate suggestion by reviewdog
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: update-dependabot
        fail_on_error: true
    - name: Checkout submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Run go build and test
      run: |
        if [ find . -name '*.go' ] ; then
          sudo apt update && sudo apt install -y golang-go &&
          go build ./... &&
          go test ./...
        fi
      shell: bash
    - name: Run gofmt
      run: |
        if [ find . -name '*.go' ] ; then
          sudo apt update && sudo apt install -y golang-go &&
          go fmt ./...
        fi
      shell: bash
    - name: Generate suggestion by reviewdog
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: go fmt
        fail_on_error: true
    - name: Run cmake-format
      run: |
        if [ -d .format ] && [ -n "$(find . -not -path './.format/*' \( -type f -o -type l \) -name '.cmake-format.py')" ] ; then
          sudo apt update && sudo apt install -y pip &&
          pip install --user cmake-format pyyaml &&
          find . -type f -a \( -name CMakeLists.txt -o -iname '*.cmake' \) -exec cmake-format -i \{\} \;
        fi
      shell: bash
    - name: Generate suggestion by reviewdog
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: cmake-format
        fail_on_error: true
    - name: Find clang-format files
      run: |
        if [ -f .clang-format ]; then
          echo "NEED_CLANG_FORMAT=True" >> $GITHUB_ENV
        fi
      shell: bash
    - name: The demo step has failed
      uses: DoozyX/clang-format-lint-action@v0.16.2
      if: ${{ env.NEED_CLANG_FORMAT == 'True' }}
      with:
        source: '.'
        exclude: './third_party ./external ./3rd_party'
        extensions: 'c,cpp,cxx,cc,h,hpp,hh'
        clangFormatVersion: 16
        inplace: True
    - name: Generate suggestion by reviewdog
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: clang-format
        fail_on_error: true
    - name: Checkout histroy
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Lint commit message
      uses: wagoid/commitlint-github-action@v5
      with:
        configFile:
          .format/commitlint.config.js
