name: "Auto release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: "ubuntu-latest"
    permissions:
       contents: write
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
      - name: Get current tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Dispatch to publish
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Auto publish
          inputs: |
            {
              "TAG_NAME": "${{ env.RELEASE_VERSION }}"
            }
